import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the repository.
*/
`;

const prod = process.argv[2] === "production";
const targetVaultPath = '/home/leo-vaderloop/Documentos/Vault_Personal_Obsidian/.obsidian/plugins/obsidian-ai-copilot';

const copyPlugin = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd(() => {
			if (!prod) {
				try {
					if (!fs.existsSync(targetVaultPath)) {
						fs.mkdirSync(targetVaultPath, { recursive: true });
					}
					fs.copyFileSync('main.js', path.join(targetVaultPath, 'main.js'));
					fs.copyFileSync('manifest.json', path.join(targetVaultPath, 'manifest.json'));
					if (fs.existsSync('styles.css')) {
						fs.copyFileSync('styles.css', path.join(targetVaultPath, 'styles.css'));
					}
					console.log('✅ Plugin copiado automáticamente al Vault de Google Drive');
				} catch (err) {
					console.error('Error al copiar el plugin:', err);
				}
			}
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
